# Generated by Django 5.0.6 on 2024-07-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('entrance', 'Entrance'), ('exit', 'Exit')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='price',
            field=models.IntegerField(),
        ),
    ]
