# Generated by Django 5.0.6 on 2024-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactions_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
