# Generated by Django 5.0.6 on 2024-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactions_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
